export const ADD_XY_POINT = 'ADD_XY_POINT';
export const REMOVE_XY_POINT = 'REMOVE_XY_POINT';
export const EDIT_XY_POINT = 'EDIT_XY_POINT';
export const REMOVE_ALL_XY_POINTS = 'REMOVE_ALL_XY_POINTS';

export const ADD_NAMEANDVALUE_POINT = 'ADD_NAMEANDVALUE_POINT';
export const REMOVE_NAMEANDVALUE_POINT = 'REMOVE_NAMEANDVALUE_POINT';
export const EDIT_NAMEANDVALUE_POINT = 'EDIT_NAMEANDVALUE_OINT';
export const REMOVE_ALL_NAMEANDVALUE_POINT =  'REMOVE_ALL_NAMEANDVALUE_POINT';

export const ADD_PAIR = 'ADD_PAIR';
export const REMOVE_PAIR = 'REMOVE_PAIR';
export const EDIT_PAIR = 'EDIT_PAIR';

export const SET_SELECTED_CHARTS_FAMILY = 'SET_SELECTED_CHARTS_FAMILY';

export const SET_X_LABEL = 'SET_X_LABEL';
export const SET_Y_LABEL = 'SET_Y_LABEL';
export const SET_NAME_LABEL = 'SET_NAME_LABEL';
export const SET_VALUE_LABEL = 'SET_VALUE_LABEL';

export const SET_HELP_VISIBLE = "SET_HELP_VISIBLE";