export const ADD_XY_POINT = 'ADD_XY_POINT';
export const REMOVE_XY_POINT = 'REMOVE_XY_POINT';
export const EDIT_XY_POINT = 'EDIT_XY_POINT';

export const ADD_NAMEANDVALUE_POINT = 'ADD_NAMEANDVALUE_POINT';
export const REMOVE_NAMEANDVALUE_POINT = 'REMOVE_NAMEANDVALUE_POINT';
export const EDIT_NAMEANDVALUE_POINT = 'EDIT_NAMEANDVALUE_OINT';

export const ADD_PAIR = 'ADD_PAIR';
export const REMOVE_PAIR = 'REMOVE_PAIR';
export const EDIT_PAIR = 'EDIT_PAIR';